# 服务名
spring:
  application:
    name: beacon-test
  # nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 47.120.25.129:8848
  # datasource
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://43.136.43.89:3306/beacon?characterEncoding=utf-8&useSSL=false
    username: root
    password: xpy3464..
# 端口号
server:
  port: 20000

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true